apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: openshift-pipelines-operator
    version: 5.0.5-779
  name: tekton-operator
spec:
  ports:
    - name: http-metrics
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: openshift-pipelines-operator
    name: openshift-pipelines-operator
status:
  loadBalancer: {}
