name: operator-update-images

on:
  workflow_dispatch: {}
  schedule:
  - cron: "0 1 * * *" # At 1AM everyday

jobs:

  update-csv:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'openshift-pipelines' # do not run this elsewhere
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Checkout the current repo
      uses: actions/checkout@v4
      with:
        ref: next

    - name: update-image-references
      run: |
        # Update operator's payload and stuff
        make update-reference   

    - name: Commit new changes
      run: |
        git config user.name openshift-pipelines-bot
        git config user.email pipelines-extcomm@redhat.com
        git checkout -b actions/update/operator-update-images-next

        git add -f  head .konflux

        if [[ -z $(git status --porcelain --untracked-files=no) ]]; then
          echo "No change, exiting"
          exit 0
        fi

        git commit -F- <<EOF
        [bot] update-CSV-images as per project.yaml

            $ git diff --stat ${NEW_COMMIT}..${OLD_COMMIT}
        $(cat /tmp/diff.txt | sed 's/^/    /' | head -c 55555)
        
        https://github.com/tektoncd/operator/compare/${NEW_COMMIT}..${OLD_COMMIT}
        EOF
        
        git push -f origin actions/update/operator-update-images-next

        if [ "$(gh pr list --base next --head actions/update/operator-update-images-next --json url --jq 'length')" = "0" ]; then
          echo "creating PR..."
          gh pr create -B next -H actions/update/operator-update-images-next --label=automated --fill
        else
          echo "a PR already exists, editing..."
          gh pr edit --title "[bot] Updating CSVs" --body "$(cat /tmp/diff.txt | sed 's/^/    /' | head -c 55555)"
        fi
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
