name: update-sources-release-v1.17.x

on:
  workflow_dispatch: {}
  schedule:
  - cron: "30 */3 * * *" # At minute 30 past every 3rd hour.

jobs:

  update-sources:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'openshift-pipelines' # do not run this elsewhere
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Checkout the current repo
      uses: actions/checkout@v4
      with:
        ref: release-v1.17.x

    - name: Clone tektoncd/operator
      run: |
        rm -fR upstream
        git clone https://github.com/tektoncd/operator upstream
        pushd upstream
        git checkout -B main origin/main
        popd

    - name: Commit new changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout -b actions/update/sources-release-v1.17.x
        pushd upstream
        OLD_COMMIT=$(cat ../head)
        NEW_COMMIT=$(git rev-parse HEAD)
        echo Previous commit: ${OLD_COMMIT}
        git show --stat ${OLD_COMMIT}
        echo New commit: ${NEW_COMMIT}
        git show --stat ${NEW_COMMIT}
        git diff --stat ${NEW_COMMIT}..${OLD_COMMIT} > /tmp/diff.txt
        git rev-parse HEAD > ../head
        popd
        rm -rf upstream/.git
        git add upstream head

        if [[ -z $(git status --porcelain --untracked-files=no) ]]; then
          echo "No change, exiting"
          exit 0
        fi

        git commit -F- <<EOF
        [bot] Update from tektoncd/operator to ${NEW_COMMIT}

            $ git diff --stat ${NEW_COMMIT}..${OLD_COMMIT}
        $(cat /tmp/diff.txt | sed 's/^/    /')
        
        https://github.com/tektoncd/operator/compare/${NEW_COMMIT}..${OLD_COMMIT}
        EOF
        
        git push -f origin actions/update/sources-release-v1.17.x

        if [ "$(gh pr list --base release-v1.17.x --head actions/update/sources-release-v1.17.x --json url --jq 'length')" = "0" ]; then
          echo "creating PR..."
          gh pr create -B release-v1.17.x -H actions/update/sources-release-v1.17.x --fill
        else
          echo "a PR already exists, skipping..."
        fi
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
